name: CI/CD Node.js with Cypress - DevTest

on:
  push:
    branches:
      - main
      - Dev # Ajustado a tu nombre real de rama
  pull_request:
    branches:
      - main
      - Dev
  workflow_dispatch:

env:
  # Esto quita el warning de Node.js 20
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_test:
    name: Build + Cypress
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Tu app puede seguir en 20, no hay problema
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        env:
          CI: false  # <-- Esto evita que los warnings detengan el build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          NODE_ENV: test # <-- SOLUCIÓN AL ERROR: Le dice a react-scripts que estamos probando
        with:
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          # Usamos wildcards (*) para ejecutar todos los archivos que empiecen con "integracion-"
          spec: cypress/e2e/integracion-*.cy.js 

      # ==========================================
      # RECOMENDACIÓN DE CALIDAD (Evidencias)
      # ==========================================
      - name: Guardar Capturas de Pantalla (si falla)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Guardar Videos de las Pruebas
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore