name: Pruebas Unitarias Dinámicas

on:
  push:
    branches:
      - 'Dev_DT_*'

jobs:
  cypress-dynamic-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          # 1. ACTUALIZADO: Cambiamos a Node 20 para soportar Cypress 15+ y React Router 7+
          node-version: '20'

      - name: Instalar dependencias
        # Mantenemos nuestra instalación con legacy-peer-deps
        run: npm install --legacy-peer-deps

      - name: Construir la aplicación (Frontend)
        run: npm run build
        env:
          CI: false

      - name: Determinar archivo de prueba según la rama
        id: set-target
        run: |
          RAMA="${{ github.ref_name }}"
          NUMERO=$(echo "$RAMA" | grep -oE '[0-9]+')
          ARCHIVO="src/**/prueba-unitaria-DT${NUMERO}.cy.*"
          
          echo "La rama actual es: $RAMA"
          echo "Buscando pruebas en: $ARCHIVO"
          echo "test_file=$ARCHIVO" >> $GITHUB_OUTPUT

      - name: Ejecutar prueba unitaria de la unidad (Component Testing)
        uses: cypress-io/github-action@v6
        with:
          install: false 
          component: true
          spec: ${{ steps.set-target.outputs.test_file }}
        env:
          # Inyectamos la variable directamente en el contenedor de GitHub
          NODE_ENV: development